x-default-logging: &logging
  driver: 'json-file'
  options:
    max-size: '5m'
    max-file: '2'

services:
    # OpenTelemetry Collector
  otelcol:
    image: ghcr.io/liatrio/liatrio-otel-collector:0.61.0-arm64
    container_name: otel-col
    deploy:
      resources:
        limits:
          memory: 125M
    env_file: .env
    restart: unless-stopped
    command: ['--config=/etc/otelcol-config.yml']
    volumes:
      - ./configs/otelcollector/otelcol-config.yml:/etc/otelcol-config.yml
    ports:
      - '4317:4317' # OTLP over gRPC receiver
      - '4318:4318' # OTLP over HTTP receiver
    logging:
      *logging
      #environment:
      #  - ENVOY_PORT
    profiles:
      - 'telemetry'